### ISSUE TITLE
(Not a issue) Special thanks to this repo give me help!

### ISSUE THREAD

**Issue by yaobo-stx** [bitfaced/Bitfaced-Web-App#22]
Dear all,

I want to special thanks to you.

Because `evergreen-ui` is a dynamically generated the styles, so every time page load, it will be non-style before loaded.

I have browsed a lot of websites and references, but haven't found a solution. maybe that there are too few users of `evergreen-ui`.

Until I saw the `_document.js` in this repository, I finally knew how to solve it and worked.

Thank you again!

**Comment by naed11** [comment]
Hey @yaobo-stx, we are very pleased you were able to learn from our codebase.  Good luck in all your development!
